"""Tests for technology fingerprint module."""
from unittest.mock import Mock
from scanner.modules.fingerprint import (
    _check_header_techs,
    _check_html_techs,
    _check_cookie_techs,
    _detect_waf,
    FingerprintModule,
)


class TestHeaderTechs:
    def test_detects_nginx(self):
        techs = _check_header_techs({"Server": "nginx/1.25.0"})
        assert "nginx" in techs

    def test_detects_apache(self):
        techs = _check_header_techs({"Server": "Apache/2.4.57 (Ubuntu)"})
        assert "Apache" in techs

    def test_detects_php(self):
        techs = _check_header_techs({"X-Powered-By": "PHP/8.1"})
        assert "PHP" in techs

    def test_detects_cloudflare(self):
        techs = _check_header_techs({"Server": "cloudflare"})
        assert "Cloudflare" in techs

    def test_unknown_header_returns_empty(self):
        techs = _check_header_techs({"Server": "UnknownProxy/1.0"})
        assert len(techs) == 0


class TestHtmlTechs:
    def test_detects_wordpress(self):
        html = '<link rel="stylesheet" href="/wp-content/themes/twenty/style.css">'
        techs = _check_html_techs(html)
        assert "WordPress" in techs

    def test_detects_react(self):
        html = '<div id="react-root"></div><script src="react.production.min.js">'
        techs = _check_html_techs(html)
        assert "React" in techs

    def test_detects_jquery(self):
        html = '<script src="jquery-3.7.1.min.js"></script>'
        techs = _check_html_techs(html)
        assert "jQuery" in techs

    def test_plain_html_returns_empty(self):
        techs = _check_html_techs("<html><body><p>Hello</p></body></html>")
        assert len(techs) == 0


class TestCookieTechs:
    def test_detects_php_session(self):
        techs = _check_cookie_techs({"Set-Cookie": "PHPSESSID=abc123; path=/"})
        assert "PHP Session" in techs

    def test_detects_laravel(self):
        techs = _check_cookie_techs({"Set-Cookie": "laravel_session=xyz"})
        assert "Laravel" in techs

    def test_unknown_cookie_returns_empty(self):
        techs = _check_cookie_techs({"Set-Cookie": "custom=value"})
        assert len(techs) == 0


class TestDetectWaf:
    def test_detects_cloudflare(self):
        headers = {"Server": "cloudflare", "CF-Ray": "abc123"}
        html = "<html>Checking your browser</html>"
        wafs = _detect_waf(headers, html)
        assert any(w["waf"] == "Cloudflare" for w in wafs)

    def test_detects_modsecurity(self):
        headers = {}
        html = "This error was generated by Mod_Security"
        wafs = _detect_waf(headers, html)
        assert any(w["waf"] == "ModSecurity" for w in wafs)

    def test_no_waf_returns_empty(self):
        headers = {"Server": "nginx"}
        html = "<html><body>Welcome</body></html>"
        wafs = _detect_waf(headers, html)
        assert len(wafs) == 0

    def test_cloudflare_waf_has_bypass_tips(self):
        headers = {"Server": "cloudflare", "CF-Ray": "abc"}
        html = "Checking your browser"
        wafs = _detect_waf(headers, html)
        cf = [w for w in wafs if w["waf"] == "Cloudflare"][0]
        assert len(cf["bypass_tips"]) > 0
        assert cf["confidence"] == "high"


class TestFingerprintModule:
    def test_module_attributes(self):
        m = FingerprintModule()
        assert m.name == "fingerprint"
        assert m.requires_url is True
        assert "fingerprint" in m.description.lower()

    def test_recommends_modules_for_php(self):
        rec = FingerprintModule._recommend_modules(
            {"PHP", "PHP Session", "nginx"}, [], None
        )
        assert "sqli" in rec
        assert "lfi" in rec
        assert "headers" in rec

    def test_waf_discards_reflected_xss(self):
        rec = FingerprintModule._recommend_modules(
            {"PHP"},
            [{"waf": "Cloudflare", "confidence": "high", "bypass_tips": []}],
            None
        )
        assert "xss" not in rec
        assert "dom_xss" in rec
