"""Technology fingerprint and WAF detection — passive analysis of headers, HTML, cookies.

Runs as a non-invasive first-pass module. Output feeds into targeted module selection.
"""
import re
import hashlib
import urllib.parse
from urllib.parse import urljoin

from scanner.modules.base import BaseModule

# ── Server → Technology mapping ────────────────────────────────────────

HEADER_TECHS = {
    "Server": {
        "Apache": ["apache", "apache/2", "apache/1"],
        "nginx": ["nginx", "nginx/1"],
        "IIS": ["microsoft-iis", "iis/7", "iis/8", "iis/10"],
        "Cloudflare": ["cloudflare"],
        "Netlify": ["netlify"],
        "Vercel": ["vercel", "now/"],
        "Heroku": ["heroku"],
        "Caddy": ["caddy"],
        "LiteSpeed": ["litespeed"],
        "Tomcat": ["apache-coyote", "tomcat"],
        "Gunicorn": ["gunicorn"],
        "uWSGI": ["uwsgi"],
    },
    "X-Powered-By": {
        "PHP": ["php/"],
        "ASP.NET": ["asp.net"],
        "Express": ["express"],
        "Next.js": ["next.js"],
        "Nuxt.js": ["nuxt"],
        "Warp": ["warp"],
    },
    "X-Generator": {
        "Drupal": ["drupal"],
    },
    "X-Drupal-Cache": {
        "Drupal": [""],  # any value
    },
    "X-Drupal-Dynamic-Cache": {
        "Drupal": [""],
    },
}

HTML_TECHS = [
    # CMS
    ("WordPress", [r"/wp-content/", r"/wp-includes/", r'name="generator"\s+content="WordPress']),
    ("Drupal", [r"/sites/default/", r"/misc/drupal\.js", r'name="Generator"\s+content="Drupal']),
    ("Joomla", [r"/media/jui/", r"/templates/.*joomla", r'name="generator"\s+content="Joomla']),
    ("Magento", [r"/skin/frontend/", r"/js/mage/", r"Magento\."]),
    ("Shopify", [r"cdn\.shopify\.com", r"Shopify\.theme"]),
    # Frameworks
    ("Laravel", [r"laravel_session"]),
    ("Django", [r"csrftoken", r"django\.admin"]),
    ("Ruby on Rails", [r'<meta\s+name="csrf-param"', r"rails-ujs"]),
    ("React", [r'react(-\d|\.prod|\.dev)', r'react-root', r'__REACT_']),
    ("Vue.js", [r'vue\.js', r'vue\.runtime', r'v-bind:', r'data-v-[\da-f]{8}']),
    ("Angular", [r'angular\.js', r'ng-app=', r'ng-version=', r'_nghost-']),
    ("Next.js", [r'__NEXT_DATA__', r'/_next/static/']),
    ("Nuxt.js", [r'__NUXT__', r'/_nuxt/']),
    ("jQuery", [r'jquery[.-]\d+\.\d+\.\d+', r'jquery\.min\.js']),
    ("Bootstrap", [r'bootstrap[.-]\d+\.\d+\.\d+', r'bootstrap\.min\.css']),
    ("Tailwind CSS", [r'tailwindcss', r'tailwind\.css']),
    # Build tools
    ("Webpack", [r'webpackJsonp', r'webpack\.hot-update']),
    ("Vite", [r'vite\.js', r'@vite/']),
    # Analytics
    ("Google Analytics", [r'google-analytics\.com/analytics\.js', r'gtag\(']),
    ("Google Tag Manager", [r'googletagmanager\.com']),
    ("Cloudflare Analytics", [r'cloudflareinsights\.com']),
    # CDN
    ("Cloudflare CDN", [r'cdn-cgi/', r'cloudflare\.com/cdn-cgi']),
    ("jsDelivr", [r'cdn\.jsdelivr\.net']),
    ("unpkg", [r'unpkg\.com']),
]

# Favicon hash → technology (MurmurHash3 of favicon.ico, base64-encoded)
FAVICON_HASHES = {
    # Hashes are standard fingerprint values from known software
    "742008816": "Nginx default",
    "1542654673": "Apache default",
    "146678891": "WordPress",
    "180732787": "Drupal 7",
    "481512437": "Joomla",
    "716989679": "Jenkins",
    "306939013": "PHPMyAdmin",
    "667284326": "Tomcat",
    "1681975209": "GitLab",
    "79649270": "Confluence",
    "1668183286": "Jira",
    "782789487": "Spring Boot",
    "-1414475558": "Django",
    "-806253852": "IIS",
    "-1814307307": "Shopify",
    "394005539": "Cpanel",
    "935026984": "Webmin",
    "1174841451": "Cisco Router",
    "1126434043": "VMware",
    "1221759509": "Citrix NetScaler",
    "-783902470": "RabbitMQ",
    "420473080": "Kibana",
    "-1404114639": "Elasticsearch",
    "603314598": "Grafana",
    "-221224965": "Prometheus",
}

# ── WAF Detection ───────────────────────────────────────────────────────

WAF_SIGNATURES = [
    # (WAF name, header patterns, block-page body patterns, bypass tips)
    {
        "name": "Cloudflare",
        "headers": {"Server": ["cloudflare"], "CF-Ray": [], "CF-Cache-Status": [], "cf-chl-out": []},
        "body": [r"cloudflare", r"cf-browser-verification", r"attention required.*cloudflare",
                 r"Checking your browser", r"cf-error-code", r"cf-challenge"],
        "bypass": ["Try origin IP directly (bypass CDN)", "Use HTTP/1.0 (no chunked)", "Try WebSocket upgrade header"],
    },
    {
        "name": "AWS CloudFront / WAF",
        "headers": {"X-Amz-Cf-Id": [], "X-Amz-Cf-Pop": [], "X-Amzn-RequestId": [], "X-Amzn-WAF-": []},
        "body": [r"aws.*waf", r"Request ID:.*amazon", r"Generated by cloudfront"],
        "bypass": ["Try origin IP directly", "Use X-Forwarded-For spoofing", "Try HTTP/2 → HTTP/1.1 downgrade"],
    },
    {
        "name": "Akamai",
        "headers": {"X-Akamai-Transformed": [], "X-Akamai-Request-ID": [], "X-Akamai-Edge": []},
        "body": [r"akamai", r"reference #[\d.]+"],
        "bypass": ["Find non-Akamai hostnames", "Try different edge IPs", "Use HTTP request smuggling"],
    },
    {
        "name": "Fastly",
        "headers": {"X-Served-By": [], "X-Cache": [], "X-Cache-Hits": [], "X-Timer": [], "Fastly-": []},
        "body": [r"fastly"],
        "bypass": ["Find origin IP", "Cache poisoning via unkeyed headers"],
    },
    {
        "name": "Imperva / Incapsula",
        "headers": {"X-Iinfo": [], "X-CDN": ["Incapsula"]},
        "body": [r"incapsula.*incident", r"_Incapsula_Resource", r"incap_ses_", r"visid_incap_"],
        "bypass": ["URL encoding variations", "Header injection", "Try WebSocket"],
    },
    {
        "name": "F5 BIG-IP ASM",
        "headers": {"X-WA-Info": [], "X-ASM-": [], "X-Request-Id": []},
        "body": [r"The requested URL was rejected", r"Reference ID.*security\.f5"],
        "bypass": ["HTTP/2 downgrade", "Chunked transfer encoding", "Parameter pollution"],
    },
    {
        "name": "Fortinet FortiWeb",
        "headers": {"FortiWeb": [], "X-FortiWeb-": []},
        "body": [r"fortigate", r"fortiweb", r"blocked by fortiweb"],
        "bypass": ["HTTP method override", "Content-Type tampering"],
    },
    {
        "name": "Barracuda WAF",
        "headers": {"X-Barracuda-": []},
        "body": [r"barracuda.*waf", r"barracuda.*blocked"],
        "bypass": ["Multipart boundary tricks", "Double URL encoding"],
    },
    {
        "name": "Citrix NetScaler",
        "headers": {"X-Citrix-": [], "X-NetScaler-": []},
        "body": [r"netscaler", r"citrix.*gateway"],
        "bypass": ["HTTP request smuggling", "HTTP/2 downgrade"],
    },
    {
        "name": "ModSecurity",
        "headers": {},
        "body": [r"mod_security", r"modsecurity", r"ModSecurity.*blocked", r"This error was generated by Mod_Security"],
        "bypass": ["Multipart bypass", "Parameter pollution", "HTTP verb tampering"],
    },
    {
        "name": "Sucuri",
        "headers": {"X-Sucuri-ID": [], "X-Sucuri-Cache": [], "Sucuri/Cloudproxy": []},
        "body": [r"sucuri", r"Access Denied - Sucuri Website Firewall"],
        "bypass": ["Find origin IP", "Try HTTPS → HTTP"],
    },
    {
        "name": "Wordfence",
        "headers": {},
        "body": [r"Wordfence", r"Generated by Wordfence"],
        "bypass": ["Brute-force slowing isn't bypassable — use distributed IPs"],
    },
    {
        "name": "Varnish (caching proxy)",
        "headers": {"X-Varnish": [], "Via": ["varnish", "Varnish"]},
        "body": [],
        "bypass": ["Cache poisoning via X-Forwarded-Host", "Double Host header"],
    },
    {
        "name": "Envoy Proxy",
        "headers": {"X-Envoy-": [], "X-Request-Id": []},
        "body": [],
        "bypass": ["HTTP/2 HPACK tricks", "Large header values"],
    },
    {
        "name": "Squid Proxy",
        "headers": {"X-Squid-Error": [], "X-Cache": ["HIT from"]},
        "body": [],
        "bypass": ["CRLF injection in URL", "Cache poisoning"],
    },
]


def _calculate_favicon_hash(favicon_bytes):
    """Simple djb2-like hash for favicon bytes. Returns string hash."""
    # Use a portable hash that matches known fingerprints
    h = 0
    for byte in favicon_bytes:
        h = ((h * 31) + byte) & 0xFFFFFFFF
    return str(h - 0x100000000 if h > 0x7FFFFFFF else h)


def _check_header_techs(resp_headers):
    """Parse response headers for technology signatures. Returns list of techs."""
    techs = set()
    for header_name, tech_map in HEADER_TECHS.items():
        value = resp_headers.get(header_name, "")
        if not value:
            continue
        value_lower = value.lower() if isinstance(value, str) else ""
        for tech, patterns in tech_map.items():
            for pattern in patterns:
                if pattern.lower() in value_lower:
                    techs.add(tech)
                    break
    return sorted(techs)


def _check_html_techs(html):
    """Parse HTML for technology patterns. Returns list of techs."""
    techs = set()
    for tech, patterns in HTML_TECHS:
        for pattern in patterns:
            if re.search(pattern, html, re.IGNORECASE):
                techs.add(tech)
                break
    return sorted(techs)


def _check_cookie_techs(resp_headers):
    """Parse Set-Cookie for framework-specific cookie names."""
    techs = set()
    cookie_hints = {
        "PHPSESSID": "PHP Session",
        "JSESSIONID": "Java/Tomcat",
        "ASP.NET_SessionId": "ASP.NET",
        "ASPSESSIONID": "ASP Classic",
        "CFID": "ColdFusion",
        "CFTOKEN": "ColdFusion",
        "laravel_session": "Laravel",
        "sessionid": "Django",
        "connect.sid": "Express/Node.js",
        "rack.session": "Ruby/Rack",
        "_oauth2_proxy": "OAuth2 Proxy",
        "mod_auth_openidc_session": "mod_auth_openidc",
    }
    cookies = resp_headers.get("Set-Cookie", "")
    if not isinstance(cookies, str):
        cookies = str(cookies)
    for name, tech in cookie_hints.items():
        if name.lower() in cookies.lower():
            techs.add(tech)
    return sorted(techs)


def _detect_waf(resp_headers, html):
    """Detect WAF from headers and body. Returns list of (name, confidence, bypass_tips)."""
    findings = []
    for sig in WAF_SIGNATURES:
        # Check headers
        header_match = False
        for hdr_name, patterns in sig["headers"].items():
            if hdr_name in resp_headers or any(
                h.lower().startswith(hdr_name.lower()) for h in resp_headers
            ):
                # Match if specific pattern or wildcard (empty list = any value)
                if not patterns:
                    header_match = True
                else:
                    val = resp_headers.get(hdr_name, "")
                    if any(p.lower() in str(val).lower() for p in patterns):
                        header_match = True

        # Check body
        body_match = any(re.search(pat, html, re.IGNORECASE) for pat in sig["body"])

        if header_match or body_match:
            confidence = "high" if (header_match and body_match) else "medium"
            findings.append({
                "waf": sig["name"],
                "confidence": confidence,
                "header_match": header_match,
                "body_match": body_match,
                "bypass_tips": sig["bypass"],
            })

    return findings


class FingerprintModule(BaseModule):
    """Passive technology fingerprint and WAF detection.

    Runs first to identify: server, language, framework, CDN, CMS, WAF.
    Results can guide subsequent targeted module selection.
    """

    name = "fingerprint"
    description = "Detect technology stack, CDN, and WAF via passive fingerprinting"
    requires_url = True

    def run(self, target, request_handler, output):
        target = target.rstrip("/")
        output.log_progress(f"Fingerprinting {target}...")

        findings = []

        try:
            resp = request_handler.get(target)
            headers = resp.headers
            html = resp.text or ""
            status = resp.status_code
        except Exception:
            output.log_progress(f"Failed to fetch {target}")
            return {"module": self.name, "findings": []}

        result = {
            "url": target,
            "status_code": status,
        }

        # ── Server detection ─────────────────────────────────
        header_techs = _check_header_techs(headers)
        if header_techs:
            result["server_techs"] = header_techs

        # ── Cookie-based detection ───────────────────────────
        cookie_techs = _check_cookie_techs(headers)
        if cookie_techs:
            result["session_techs"] = cookie_techs

        # ── HTML-based detection ─────────────────────────────
        html_techs = _check_html_techs(html)
        if html_techs:
            result["html_techs"] = html_techs

        # ── CDN detection ────────────────────────────────────
        cdn_headers = {
            "CF-Ray": "Cloudflare",
            "X-Cache": "Fastly/Varnish",
            "X-Served-By": "Fastly",
            "X-Akamai-Transformed": "Akamai",
            "Server-Timing": "CDN (various)",
            "X-CDN": "Generic CDN",
            "X-Edge-": "Generic CDN edge",
            "X-Proxy-Cache": "Generic CDN cache",
        }
        detected_cdn = None
        for hdr, label in cdn_headers.items():
            if hdr in headers or any(k.lower().startswith(hdr.lower()) for k in headers):
                detected_cdn = label
                break
        if detected_cdn:
            result["cdn"] = detected_cdn

        # ── WAF detection ────────────────────────────────────
        wafs = _detect_waf(headers, html)
        if wafs:
            result["wafs"] = wafs
            # Log each WAF found
            for w in wafs:
                output.log_progress(
                    f"  WAF detected: {w['waf']} (confidence: {w['confidence']})"
                )
                for tip in w["bypass"]:
                    output.log_progress(f"    ↳ {tip}")

        # ── Summarize tech stack ─────────────────────────────
        all_techs = set()
        for key in ("server_techs", "session_techs", "html_techs"):
            all_techs.update(result.get(key, []))
        if all_techs:
            result["all_techs"] = sorted(all_techs)
            output.log_progress(f"  Tech stack: {', '.join(sorted(all_techs))}")

        if detected_cdn:
            output.log_progress(f"  CDN: {detected_cdn}")

        result["recommended_modules"] = self._recommend_modules(all_techs, wafs, detected_cdn)

        findings.append(result)
        output.log_finding(self.name, result)

        if result.get("recommended_modules"):
            rec = result["recommended_modules"]
            output.log_progress(f"  Recommended modules: {', '.join(rec)}")

        return {"module": self.name, "findings": findings}

    @staticmethod
    def _recommend_modules(techs, wafs, cdn):
        """Suggest scanner modules based on detected tech stack."""
        rec = set()
        tech_str = " ".join(techs).lower()

        # Always useful
        rec.update(["headers", "cors"])

        # CMS-specific
        if any(t in techs for t in ("WordPress",)):
            rec.update(["dirscan", "sqli", "xss"])
        if any(t in techs for t in ("Drupal",)):
            rec.update(["dirscan", "sqli", "xss"])
        if any(t in techs for t in ("Joomla",)):
            rec.update(["dirscan", "sqli", "xss"])
        if any(t in techs for t in ("Magento",)):
            rec.update(["dirscan", "sqli"])

        # Language-specific
        if any(t in techs for t in ("PHP", "PHP Session")):
            rec.update(["sqli", "lfi", "cmdi"])
        if any(t in techs for t in ("Java/Tomcat",)):
            rec.update(["sqli", "ssti", "ssrf"])
        if any(t in techs for t in ("ASP.NET", "ASP Classic", "IIS")):
            rec.update(["sqli", "cmdi"])
        if any(t in techs for t in ("Python", "Django", "Flask", "Express/Node.js")):
            rec.update(["sqli", "ssti", "ssrf"])
        if any(t in techs for t in ("Ruby on Rails", "Ruby/Rack")):
            rec.update(["sqli", "ssrf"])

        # Framework-specific
        if "Laravel" in tech_str:
            rec.add("dirscan")
        if "Django" in tech_str:
            rec.add("dirscan")
        if "React" in tech_str or "Vue.js" in tech_str or "Angular" in tech_str:
            rec.update(["dom_xss", "params"])
        if "Next.js" in tech_str or "Nuxt.js" in tech_str:
            rec.update(["ssrf"])

        # WAF-aware adjustments
        if any(w["waf"] in ("Cloudflare", "ModSecurity") for w in wafs):
            # These WAFs block most injection payloads — suggest subtler approaches
            rec.discard("xss")  # reflected XSS mostly blocked
            rec.add("dom_xss")   # DOM XSS bypasses WAF
            rec.add("csrf")      # passive, won't trigger WAF
            rec.add("redirect")  # open redirect often bypasses WAF

        # CDN-aware
        if cdn:
            rec.add("subdomain")  # find origin hosts that might bypass CDN

        # Remove what doesn't make sense for static sites
        if "Cloudflare CDN" in tech_str and not any(
            t in techs for t in ("PHP", "Java/Tomcat", "ASP.NET", "Django", "Ruby on Rails")
        ):
            rec.discard("sqli")
            rec.discard("cmdi")

        return sorted(rec)
